### ISSUE TITLE
Can't find the main class

### ISSUE THREAD

**Issue by LynnHtt** [faysal515/Java-Simple-Hotel-Management#2]
Would you please tell me the path to the main class pls?

**Comment by faysal515** [comment]
Every UI form comes with the main function. this project was created using Netbeans. You should not face a problem if you run the project directly from NetBeans. otherwise, you can try running this file as main
https://github.com/faysal515/Java-Simple-Hotel-Management/blob/master/src/I3/UI/ControlPanel.java

**Comment by LynnHtt** [comment]
Thanks I was trying with other IDE...and sorry I am new to java thst's why

**Comment by LynnHtt** [comment]
that's *
